version = 0.1

[default.deploy.parameters]
stack_name = "test5-bedrock-agent"
resolve_s3 = true
s3_prefix = "test5-bedrock-agent"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
